#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.0'
#xcodeproj 'CoinBlock.xcodeproj'

def shared_pods
platform :ios, '8.0'
	# Uncomment this line if you're using Swift or would like to use dynamic frameworks
	#use_frameworks!
	pod 'AFNetworking', '1.3.3'
	pod 'Reachability'
	pod 'OpenUDID'
	pod 'FXLabel'
	pod 'iRate'
	pod 'iNotify'
	pod 'MBProgressHUD'
    #pod 'QR-Code-Encoder-for-Objective-C'
	pod 'NSDate-Extensions'
	pod 'SVProgressHUD'
    #pod 'GoogleAnalytics-iOS-SDK'
    pod 'GoogleAnalytics'
	#pod 'JSONKit'
	#pod 'ShareKit'
	#pod 'ShareKit/Facebook'
	#pod 'ShareKit/Twitter'
	#pod 'TestFlightSDK'
	#pod 'Localytics'
    #pod 'Localytics-iOS-Client'

	#pod 'Facebook-iOS-SDK'
	#pod 'Parse', '1.5.0'
	pod 'Google-Mobile-Ads-SDK'
	pod 'ChartboostSDK'
	pod 'Flurry-iOS-SDK'

	#specific
	pod 'ALAssetsLibrary-CustomPhotoAlbum'
	pod 'NSData+Base64'
	#pod 'NSString-HTML'

	#tests
	#pod 'UIAlertView-Blocks'
	#pod 'UI7Kit'
end

target 'quoteaddict' do
    shared_pods
end



